### ISSUE TITLE
Incorrect exception handler page number

### ISSUE THREAD

**Issue by arpankapoor** [xosnitc/xosdoc#12]
Exception handler routine resides at page no. 7 (http://xosnitc.github.io/xos-spec.html#navmemorg), while [here](http://xosnitc.github.io/xsm-spec.html#navexcep) it is marked at page no. 23.

**Comment by vivekzhere** [comment]
Corrected.

**Comment by vivekzhere** [comment]
Corrected only in website. Latex and pdf need to updated
