### ISSUE TITLE
„Download as PDF“ link not correctly set

### ISSUE THREAD

**Issue by m99coder** [xosnitc/xosdoc#15]
On the page http://xosnitc.github.io/xos-spec.html there is a „Download as PDF“ link at the upper left which is pointing to https://github.com/xosnitc/xosdoc/blob/master/xos/os.pdf?raw=true and results in a 404. As you probably know it has to point to https://github.com/xosnitc/xosdoc/blob/master/xos/xos.pdf?raw=true. Just one missing x :)

**Comment by shamilcm** [comment]
Fixed. Thanks for pointing out. :)
