### ISSUE TITLE
Document Changes

### ISSUE THREAD

**Issue by vivekzhere** [xosnitc/xosdoc#4]
XSM :: IRET first changes Mode to USER mode. then does the rest. So when iret uses SP , it is logical address.

XOS :: In PCB , Open file table - invalid entry is set to -1

XOS :: System wide open file table  - invalid entry is set to -1 
XOS :: System wide open file table  - first entry name changed to "FAT Index" ( from "FAT Index Entry") .

XOS :: In system Call - change  "an error code otherwise" to "-1 otherwise" in each syscall
XFS :: Invalid FAT entry is denoted by basic block =-1

**Comment by sreerajsivadas** [comment]
XSM - changed IRET description. (pdf & site)

**Comment by sreerajsivadas** [comment]
XOS - changed per-proc table in pcb -invalid entry -1  
        - system wide table - invalid entry -1, corrected "FAT index"
        - changed error code of syscalls to -1

**Comment by sreerajsivadas** [comment]
XFS - invalid FAT: value of basic block = -1

**Comment by sreerajsivadas** [comment]
All changes made to pdf and website
